version: 2
updates:
  # Maintain dependencies for poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
