version: "3"
services:
  bot:
    image: nachomemes
    container_name: nachomemes
    build: .
    command: --local
    environment:
      - DISCORD_TOKEN
      - ACCESS_KEY
      - SECRET
      - REGION
