version: "3.8"
services:
  bot:
    container_name: nachomemes
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    environment:
      - DISCORD_TOKEN
      - ACCESS_KEY
      - SECRET
      - REGION
