
from typing import Any

class _EmptyEmbed:
    def __bool__(self): ...
    def __len__(self): ...

EmptyEmbed: Any

class EmbedProxy:
    def __init__(self, layer: Any) -> None: ...
    def __len__(self): ...
    def __getattr__(self, attr: Any): ...

class Embed:
    title: str = ...
    Empty: Any = ...
    type: Any = ...
    url: Any = ...
    description: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_dict(cls, data: Any): ...
    def copy(self): ...
    def __len__(self): ...
    @property
    def colour(self): ...
    @colour.setter
    def colour(self, value: Any) -> None: ...
    color: Any = ...
    @property
    def timestamp(self): ...
    @timestamp.setter
    def timestamp(self, value: Any) -> None: ...
    @property
    def footer(self): ...
    def set_footer(self, *, text: Any = ..., icon_url: Any = ...): ...
    @property
    def image(self): ...
    def set_image(self, url: Any): ...
    @property
    def thumbnail(self): ...
    def set_thumbnail(self, url: Any): ...
    @property
    def video(self): ...
    @property
    def provider(self): ...
    @property
    def author(self): ...
    def set_author(self, name: Any, *, url: Any = ..., icon_url: Any = ...): ...
    def remove_author(self): ...
    @property
    def fields(self): ...
    def add_field(self, name: Any, value: Any, *, inline: bool = ...): ...
    def insert_field_at(self, index: Any, name: Any, value: Any, *, inline: bool = ...): ...
    def clear_fields(self) -> None: ...
    def remove_field(self, index: Any) -> None: ...
    def set_field_at(self, index: Any, name: Any, value: Any, *, inline: bool = ...): ...
    def to_dict(self): ...
