from typing import Any

class EqualityComparable:
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class Hashable(EqualityComparable):
    def __hash__(self) -> Any: ...
