from .mixins import Hashable as Hashable
from typing import Any, Optional

class RoleTags:
    bot_id: Any = ...
    integration_id: Any = ...
    def __init__(self, data: Any) -> None: ...
    def is_bot_managed(self): ...
    def is_premium_subscriber(self): ...
    def is_integration(self): ...

class Role(Hashable):
    id: int
    name: str

    guild: Any = ...
    def __init__(self, guild: Any, state: Any, data: Any) -> None: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def is_default(self): ...
    def is_bot_managed(self): ...
    def is_premium_subscriber(self): ...
    def is_integration(self): ...
    @property
    def permissions(self): ...
    @property
    def colour(self): ...
    @property
    def color(self): ...
    @property
    def created_at(self): ...
    @property
    def mention(self): ...
    @property
    def members(self): ...
    position: Any = ...
    async def edit(self, *, reason: Optional[Any] = ..., **fields: Any) -> None: ...
    async def delete(self, *, reason: Optional[Any] = ...) -> None: ...
