import discord.abc

from typing import Any, Optional

class Profile:
    @property
    def nitro(self): ...
    premium: Any = ...
    @property
    def staff(self): ...
    @property
    def partner(self): ...
    @property
    def bug_hunter(self): ...
    @property
    def early_supporter(self): ...
    @property
    def hypesquad(self): ...
    @property
    def hypesquad_houses(self): ...
    @property
    def team_user(self): ...
    @property
    def system(self): ...

class _BaseUser:
    id: int
    name: str

class BaseUser(_BaseUser):
    def __init__(self, state: Any, data: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    @property
    def public_flags(self): ...
    @property
    def avatar_url(self): ...
    def is_avatar_animated(self): ...
    def avatar_url_as(self, *, format: Optional[Any] = ..., static_format: str = ..., size: int = ...): ...
    @property
    def default_avatar(self): ...
    @property
    def default_avatar_url(self): ...
    @property
    def colour(self): ...
    @property
    def color(self): ...
    @property
    def mention(self): ...
    def permissions_in(self, channel: Any): ...
    @property
    def created_at(self): ...
    @property
    def display_name(self) -> str: ...
    def mentioned_in(self, message: Any): ...

class ClientUser(BaseUser):
    def __init__(self, state: Any, data: Any) -> None: ...
    def get_relationship(self, user_id: Any): ...
    @property
    def relationships(self): ...
    @property
    def friends(self): ...
    @property
    def blocked(self): ...
    email: Any = ...
    async def edit(self, **fields: Any) -> None: ...
    async def create_group(self, *recipients: Any): ...
    async def edit_settings(self, **kwargs: Any): ...

class User(BaseUser, discord.abc.Messageable):
    @property
    def dm_channel(self): ...
    async def create_dm(self): ...
    @property
    def relationship(self): ...
    async def mutual_friends(self): ...
    def is_friend(self): ...
    def is_blocked(self): ...
    async def block(self) -> None: ...
    async def unblock(self) -> None: ...
    async def remove_friend(self) -> None: ...
    async def send_friend_request(self) -> None: ...
    async def profile(self): ...
