version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: "Install dependencies."
          command: sudo pip3 install -r requirements.txt pylint
      - run:
          name: "Check syntax."
          command: pylint -E *.py
      - run:
          name: "Run unit tests."
          command: python3 -m unittest
