- name: Deploy Container
  gather_facts: yes
  remote_user: ubuntu
  hosts: all
  become_method: sudo

  tasks: 
    - name: Install aptitude using apt
      apt: 
        name: aptitude 
        state: present
      become: yes
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull Docker image
      docker_image:
        repository: docker.pkg.github.com/nachomemes/nachomemes
        name: nachomemes
        tag: "{{ tag }}"
        source: pull

    - name: Run Docker Container
      docker_container:
        name: nachomeme
        image: nachomeme "{{ tag }}"
        state: present
        env:
          - PYTHONUNBUFFERED=1
          - DISCORD_TOKEN: "{{ discord_token }}"
          - ACCESS_KEY: "{{ access_key }}"
          - SECRET: "{{ aws_secret }}"
          - REGION: "{{ aws_region }}"
