name: CI
on: [push]

env:
  python-version: "3.9"
  poetry-version: "1.1.4"

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install Dependencies
        run: |
          pip install poetry==1.1.4
          poetry install
      - name: Run yamllint
        run: poetry run yamllint .

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install Dependencies
        run: |
          pip install poetry==1.1.4
          poetry install
      - name: Run Pylint
        run: poetry run pylint -E nachomemes

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install Dependencies
        run: |
          pip install poetry==1.1.4
          poetry install
      - name: Test
        run: |
          poetry run python -m unittest
