name: Deploy Bot to Staging

on: 
  push:
    branches:
# Add develop here once its ready
      - terraform
      - k8s


jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish image to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with: 
          name: nachomemes/nachomemes/nachomemes
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          snapshot: true

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET }}
          aws-region: ${{ secrets.REGION }}

      - name: Generate temp SSH keys
        run: ssh-keygen -t rsa -b 4096 -f /tmp/temp-key

      - name: Setup Temp SSH Key
        run: aws ec2-instance-connect send-ssh-public-key --instance-id {{ secrets.INSTANCE_ID_PROD }} --instance-os-user ubuntu --ssh-public-key file:///tmp/temp-key.pub --availability-zone {{ secrets.AWS_AZ }}

      - name: Run docker container
        uses: appleboy/ssh-action@master
        env: 
          DISCORD_TOKEN: "{{ secrets.DISCORD_TOKEN}}"
          ACCESS_KEY: "{{ secrets.ACCESS_KEY }}"
          SECRET: "{{ secrets.SECRET }}"
          REGION: "{{ secrets.REGION }}"
        with: 
          host: "{{ secret.HOST_PROD }}"
          username: ubuntu
          key: /tmp/temp-key
          script: docker pull docker.pkg.github.com/nachomemes/nachomemes/nachomemes:latest && docker run docker.pkg.github.com/nachomemes/nachomemes/nachomemes:latest  -e DISCORD_TOKEN -e ACCESS_KEY -e SECRET -e REGION