name: Deploy Bot to Staging

on: 
<<<<<<< HEAD
  push:
=======
  pull_request:
>>>>>>> develop
    branches:
      - develop


jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
