name: Deploy Production Bot
on:
  push:
    branches:
      - feature/k8s-deploy

jobs:
  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set K8s Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.PROD_KUBE_CONFIG }}
        id: setcontext
      - name: Deploy to K8s
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: 'nachomemes-prod'
          manifests: infrastructure/deployment.yaml
          images: ghcr.io/nachomemes/nachomemes:${{ github.sha }}