name: Deploy Bot to Staging

on: 
  push:
    branches:
      - develop
      - terraform


jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set ENV
        env: 
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret }}
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
        run: mkdir ~/.ssh/ 
      - name: Change folder perms
        run:  chmod 700 ~/.ssh/ 
      

      # Need to generate a ssh key for ansible to configure the instance oneview_logical_interconnect_group
      - name: Generate SSH Key
        run:  |
          ssh-keygen -t rsa -b 4096 -N '' -f /home/runner/.ssh/id_rsa

      - name: Run Terraform Init
        run: terraform init /home/runner/work/NachoMemes/NachoMemes/infrastructure/staging 
      
      - name: Run Terraform Plan
        run: terraform plan /home/runner/work/NachoMemes/NachoMemes/infrastructure/staging

      - name: Run Terraform Apply
        run: terraform apply -lock=true -auto-approve -refresh=true /home/runner/work/NachoMemes/NachoMemes/infrastructure/staging 
      - name: Set output  
        run: terraform output > inventory.txt
      - name: Run Deploy Playbook
        run: ansible-playbook -i inventory.txt staging-deploy.yml