name: Deploy Production Bot
on:
  push:
    branches:
      - master

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish image to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: nachomemes/nachomemes/nachomemes
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest, ${{ github.ref}}"
