name: Deploy Bot to Staging

on:
  push:
    branches:
      # Add develop here once its ready
      - terraform

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish image to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: nachomemes/nachomemes/nachomemes
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          snapshot: true
      - name: Setup SSH directory
        run: mkdir ~/.ssh/

      - name: Change folder perms
        run: chmod 700 ~/.ssh/

      # Need to generate a ssh key for ansible to configure the instance oneview_logical_interconnect_group
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -N '' -f /home/runner/.ssh/id_rsa

      - name: Run Terraform Init
        run: terraform init /home/runner/work/NachoMemes/NachoMemes/infrastructure/staging
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret }}
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}

      - name: Run Terraform Plan
        run: terraform plan -var="public_key=$(</home/runner/.ssh/id_rsa.pub)" /home/runner/work/NachoMemes/NachoMemes/infrastructure/staging
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret }}
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}

      - name: Run Terraform Apply
        run: terraform apply -lock=true -auto-approve -refresh=true -var="public_key=$(</home/runner/.ssh/id_rsa.pub)" /home/runner/work/NachoMemes/NachoMemes/infrastructure/staging
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret }}
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      - name: Set output
        run: terraform output public_ip > inventory.txt
      - name: Run Deploy Playbook
        run: ansible-playbook -i inventory.txt staging-deploy.yml --extra-vars "discord_token=${{ secrets.discord }}"
