name: Lint and Test

on:  
  push:
    branches-ignore:
      - terraform
  

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: eshork/gitleaks-action@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint -E *.py
        
    - name: Test with unittest
      run: |
        python3 -m unittest
