name: Lint and Test
on: [push]

env:
  python-version: "3.9"
  poetry-version: "1.1.4"

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install Dependencies
        run: |
          pip install poetry==1.1.4
          poetry install
      - name: Run Pylint
        run: poetry run pylint -E nachomemes

  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install poetry==1.1.4
          poetry install
      - name: Test with unittest
        run: |
          poetry run python -m unittest
      - name: Build Docker Image
        run: docker build .
