name: Lint and Test
# Runs the main linter and makes sure it passes all tests. 
on:  
  push:
    branches-ignore:

  

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint -E *.py
        
    - name: Test with unittest
      run: |
        python3 -m unittest
    - name: Build Docker Image
      run: docker buid .